export default {
  NAV_DASHBOARD: 'NAV_DASHBOARD',
  NAV_CARD_PROGRAM: 'NAV_CARD_PROGRAM',
  NAV_RESELLER: 'NAV_RESELLER',
  NAV_FLOAT_BALANCE: 'NAV_FLOAT_BALANCE',
  NAV_KEY_MODULE: 'NAV_KEY_MODULE',

  CARD_PROGRAM_EDIT: 'CARD_PROGRAM_EDIT',
  CARD_PROGRAM_VIEW: 'CARD_PROGRAM_VIEW',
  
  RESELLER_SUBSCRIPTION_VIEW: 'RESELLER_SUBSCRIPTION_VIEW',
  RESELLER_SUBSCRIPTION_EDIT: 'RESELLER_SUBSCRIPTION_EDIT',
  RESELLER_INVOICE_VIEW: 'RESELLER_INVOICE_VIEW',
  
  FLOAT_ACCOUNT_VIEW: 'FLOAT_ACCOUNT_VIEW',
  STATEMENT_VIEW: 'STATEMENT_VIEW',
  STATEMENT_DOWNLOAD: 'STATEMENT_DOWNLOAD',
  DEBIT_CREDIT_INSTRUCT_VIEW: 'DEBIT_CREDIT_INSTRUCT_VIEW',
  DEBIT_CREDIT_INSTRUCT_EDIT: 'DEBIT_CREDIT_INSTRUCT_EDIT',
  DEBIT_CREDIT_INSTRUCT_APPROVE: 'DEBIT_CREDIT_INSTRUCT_APPROVE',
  UNALLOCATED_FLOAT_VIEW: 'UNALLOCATED_FLOAT_VIEW',

  KYC_REGISTER_VIEW: 'KEY_REGISTER_VIEW',
  KYC_WORKFLOW_VIEW: 'KEY_WORKFLOW_VIEW',

  ALL_PERMISSION: 'ALL_PERMISSION'
}
